version: '3.8'

services:
  elasticsearch:
    image: elastic/elasticsearch:7.17.17
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: elastic/kibana:7.17.17
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "14268:14268"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true  # если нужен OTLP
    